<Project Sdk="Microsoft.NET.Sdk">

	<!-- Project -->
	<PropertyGroup Label="project">
		<TargetFrameworks>net7.0</TargetFrameworks>
		<LangVersion>14</LangVersion>
		<Nullable>enable</Nullable>

		<AssemblyName>OwlDomain.SDL3.LowLevel</AssemblyName>
		<RootNamespace>OwlDomain.SDL3.LowLevel</RootNamespace>
		<Version>0.0.0</Version>

		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<Deterministic>true</Deterministic>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>

		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>

		<IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net7.0'))">true</IsAotCompatible>
		<IsTrimmable Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net6.0'))">true</IsTrimmable>
	</PropertyGroup>

	<!-- NuGet package -->
	<PropertyGroup Label="nuget">
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>

		<Authors>OwlDomain</Authors>
		<Copyright>Copyright (c) OwlDomain 2026 - $([System.DateTime]::UtcNow.Year)</Copyright>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>

		<RepositoryUrl>https://github.com/Owl-Domain/sdl-cs.git</RepositoryUrl>
		<PackageProjectUrl>https://www.github.com/Owl-Domain/sdl-cs</PackageProjectUrl>

		<PackageReadmeFile>readme.md</PackageReadmeFile>
		<PackageIcon>icon.png</PackageIcon>
		<PackageReleaseNotes>$([System.IO.File]::ReadAllText("$(MSBuildProjectDirectory)/meta/changelog.md"))</PackageReleaseNotes>

		<Description>A package providing low-level C# bindings for SDL3.</Description>
		<PackageTags>sdl sdl3 bindings</PackageTags>
	</PropertyGroup>

	<!-- Package files -->
	<ItemGroup Label="content">
		<None Pack="true" PackagePath="" Include="../../icon.png" Link="meta/icon.png" />
		<None Pack="true" PackagePath="" Include="meta/readme.md" />
		<None Pack="true" PackagePath="" Include="meta/changelog.md" />
	</ItemGroup>

</Project>
